# Import Dependencies for Data Cleanup

In [1]:
import os
import pandas as pd
import numpy as np

# Import CSV Files for Data Cleanup
Create connection to csv files and load all data into a pandas dataframe. Drop unnecessary columns and any null data values.

In [4]:
aqi2019_df = pd.read_csv("Data/annual_aqi_by_county_2019.csv")
aqi2019_df.head()

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,Alabama,Baldwin,2019,166,140,26,0,0,0,0,80,54,40,0,0,139,0,27,0
1,Alabama,Clay,2019,63,58,5,0,0,0,0,67,49,29,0,0,0,0,63,0
2,Alabama,Colbert,2019,171,161,10,0,0,0,0,61,49,38,0,0,138,0,33,0
3,Alabama,DeKalb,2019,208,188,20,0,0,0,0,77,50,39,0,0,187,0,21,0
4,Alabama,Elmore,2019,148,137,11,0,0,0,0,100,49,41,0,0,148,0,0,0

In [6]:
aqi2019_df = aqi2019_df.rename(columns={"State" : "state",
                                       "County" : "county",
                                       "Year" : "year",
                                       "Days with AQI" : "days_with_aqi",
                                       "Good Days" : "good_days",
                                       "Moderate Days" : "moderate_days",
                                       "Unhealthy for Sensitive Groups Days" : "unhealthy_sensitive_days",
                                       "Unhealthy Days" : "unhealthy_days",
                                       "Very Unhealthy Days" : "very_unhealthy_days",
                                       "Hazardous Days" : "hazardous_days",
                                       "Max AQI" : "max_aqi",
                                       "90th Percentile AQI" : "90th_pct_aqi",
                                       "Median AQI" : "median_aqi",
                                       "Days CO" : "days_co",
                                       "Days NO2" : "days_no2",
                                       "Days Ozone" : "days_ozone",
                                       "Days SO2" : "days_so2",
                                       "Days PM2.5" : "days_pm2.5",
                                       "Days PM10" : "days_pm10",
                                       })
aqi2019_df.head()

,state,county,year,days_with_aqi,good_days,moderate_days,unhealthy_sensitive_days,unhealthy_days,very_unhealthy_days,hazardous_days,max_aqi,90th_pct_aqi,median_aqi,days_co,days_no2,days_ozone,days_so2,days_pm2.5,days_pm10
0,Alabama,Baldwin,2019,166,140,26,0,0,0,0,80,54,40,0,0,139,0,27,0
1,Alabama,Clay,2019,63,58,5,0,0,0,0,67,49,29,0,0,0,0,63,0
2,Alabama,Colbert,2019,171,161,10,0,0,0,0,61,49,38,0,0,138,0,33,0
3,Alabama,DeKalb,2019,208,188,20,0,0,0,0,77,50,39,0,0,187,0,21,0
4,Alabama,Elmore,2019,148,137,11,0,0,0,0,100,49,41,0,0,148,0,0,0

# Import SQLite and load dataframe onto database

In [10]:
import sqlite3

In [11]:
db = sqlite3.connect("test_db")

In [9]:
pd.DataFrame.to_sql?

In [12]:
aqi2019_df.to_sql("2019_aqi_bycounty", db, if_exists="append", index=False)